name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm build
          run: npm run test
          browser: chrome

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Test Report
          path: cypress/reports/html/index.html

